services:
  nginx:
    image: nginx:latest
    configs:
      - source: my_config
        target: /etc/nginx/conf.d

continuous_preview:
  deploy_preview_when_pull_request_is_opened: true
  delete_preview_when_pull_request_is_closed: true
  share_to_github: true

ingress:
  service: nginx
  port: 8080

configs:
  my_config:
    file: ./configs/vote.conf
